name = "notion-kv-sync"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-23"

[vars]
NOTION_DB_ID = "fbeabcb601ae4649a099635d7ac10023"

# [secrets]
# NOTION_TOKEN

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[env.development]
name = "dev-notion"
NODE_ENV = "development"

[[kv_namespaces]]
binding = "POSTS"
id = "2d1e2a90e7b2423b8b195ea4489cb641"
preview_id = "2d1e2a90e7b2423b8b195ea4489cb641"